"""Simplified caption tracks, generated by Claude on Amazon Bedrock.

Why this exists: for a viewer whose first language is a signed language,
written English is a second language, and verbatim caption speed routinely
exceeds their reading rate. A simplified track is the second half of this
project's access argument, alongside the signer layer.

Three rules this module enforces in code, not in prose:

1. **Timings are never invented.** The model rewrites cue text and nothing
   else. Cue boundaries, order and count come from the source file.
2. **A cue the model did not return keeps its original text.** Dropping a cue
   would silently remove information from an accessibility track, which is
   worse than leaving it verbatim.
3. **Output is never marked reviewed.** The caller writes these tracks through
   :meth:`stm.model.Caption.generated`, which hard-codes ``reviewed: false``.
"""

from __future__ import annotations

import logging
import os
import re
from dataclasses import dataclass, field
from typing import Any, Protocol

from stm_pipeline.captions_vtt import Cue, build_vtt, parse_vtt, word_budget

log = logging.getLogger(__name__)

#: Model IDs on the Claude in Amazon Bedrock endpoint carry an `anthropic.` prefix.
#: Access is per-model in the Bedrock console. At the time of writing Opus 5 is
#: gated and Sonnet 5 / Haiku 4.5 are open to all Bedrock customers, so if the
#: default 403s, `--bedrock-model anthropic.claude-sonnet-5` is the fallback.
DEFAULT_MODEL = "anthropic.claude-opus-5"
KNOWN_MODELS = (
    "anthropic.claude-opus-5",
    "anthropic.claude-sonnet-5",
    "anthropic.claude-haiku-4-5",
    "anthropic.claude-opus-4-8",
    "anthropic.claude-fable-5-1",
)

_MARKER = re.compile(r"^\s*\[(\d+)\]\s?(.*)$")

SYSTEM_PROMPT = """\
You rewrite television captions into a simplified English track for deaf and \
hard-of-hearing viewers.

Who reads this. Many of your readers use a signed language as their first \
language, so written English is a second language for them. Reading grade \
level strongly predicts how much of a caption they take in, and verbatim \
caption speed often runs faster than they can read. Your job is to make the \
same information reachable in the time the cue is on screen.

What to do with each cue.
- Keep every fact. Names, numbers, dates, places, quantities and negations \
stay exactly as they are. "not approved" must never become "approved".
- Prefer short, common words over long or technical ones. Prefer the plain \
verb over the nominalisation: "decided" over "reached a decision".
- One idea per sentence. Active voice, subject first. Break a long sentence \
into two short ones inside the same cue rather than keeping one long one.
- Cut filler that carries no information: "you know", "sort of", false \
starts, repeated words, "um".
- Aim at or under the word budget given for each cue. The budget is what fits \
at a comfortable reading rate in the time that cue is on screen. Going a \
little over is acceptable when cutting further would lose a fact; going well \
over is not.

What never to do.
- Never add information, opinion, explanation or context that is not in the \
source.
- Never summarise several cues into one, and never drop a cue because it \
seems unimportant.
- Never merge, split, reorder or renumber cues. One input cue produces \
exactly one output cue with the same number.
- Never translate. The output is English.
- If a cue is a speaker label, a sound description in brackets, or is already \
short and plain, return it unchanged.

Output format. Return one line per cue, in the same order, each beginning \
with its number in square brackets, exactly like the input:
[1] rewritten text
[2] rewritten text
Return nothing else. No preamble, no commentary, no blank lines between cues."""


class Simplifier(Protocol):
    """Rewrites a WebVTT transcript into simpler English, cue for cue."""

    @property
    def name(self) -> str: ...

    def simplify(self, vtt: str) -> str | None: ...


class NullSimplifier:
    """Produces nothing. The default, so the pipeline runs with no AWS account."""

    name = "none"

    def simplify(self, vtt: str) -> str | None:
        return None


@dataclass
class SimplifyStats:
    """What actually happened, so the caller can report it rather than guess."""

    cues: int = 0
    rewritten: int = 0
    kept_verbatim: int = 0
    chunks: int = 0
    retries: int = 0
    failures: list[str] = field(default_factory=list)

    @property
    def coverage(self) -> float:
        return self.rewritten / self.cues if self.cues else 0.0


def render_chunk(cues: list[Cue], words_per_second: float) -> str:
    """Numbered cue text with a per-cue word budget derived from its duration."""
    lines = []
    for cue in cues:
        budget = word_budget(cue.duration_s, words_per_second)
        flat = " ".join(cue.text.split())
        lines.append(f"[{cue.index}] (<={budget} words) {flat}")
    return "\n".join(lines)


def parse_reply(text: str, expected: set[int]) -> dict[int, str]:
    """Pull ``[n] text`` lines out of a reply, ignoring anything unexpected.

    Continuation lines with no marker are appended to the cue above, so a model
    that wraps a long rewrite does not lose half of it.
    """
    out: dict[int, str] = {}
    current: int | None = None
    for raw in text.replace("\r\n", "\n").split("\n"):
        match = _MARKER.match(raw)
        if match:
            index = int(match.group(1))
            current = index if index in expected else None
            if current is not None:
                out[current] = match.group(2).strip()
        elif current is not None and raw.strip():
            out[current] = f"{out[current]} {raw.strip()}".strip()
    return {k: v for k, v in out.items() if v}


class BedrockSimplifier:
    """Claude on Amazon Bedrock, via the Messages API endpoint.

    Uses the ``AnthropicBedrockMantle`` client, which signs with SigV4 and
    resolves credentials through the standard AWS chain -- so inside the
    extraction container it picks up the Batch job role with no configuration.

    Note for anyone extending this: structured outputs are not available on
    this endpoint, which is why the cue protocol is plain text that this module
    validates itself rather than a JSON schema.
    """

    def __init__(
        self,
        model: str = DEFAULT_MODEL,
        region: str | None = None,
        chunk_size: int = 40,
        words_per_second: float = 2.0,
        effort: str = "low",
        max_tokens: int = 16000,
        client: Any | None = None,
    ) -> None:
        self.model = model
        self.region = region or os.environ.get("AWS_REGION") or os.environ.get("AWS_DEFAULT_REGION")
        self.chunk_size = max(1, chunk_size)
        self.words_per_second = words_per_second
        self.effort = effort
        self.max_tokens = max_tokens
        self.stats = SimplifyStats()
        self._client = client

    @property
    def name(self) -> str:
        return f"amazon-bedrock:{self.model}"

    def _get_client(self) -> Any:
        if self._client is None:
            try:
                from anthropic import AnthropicBedrockMantle
            except ImportError as exc:  # pragma: no cover - depends on extras
                raise RuntimeError(
                    "Caption simplification needs the aws extra: "
                    'pip install -e ".[aws]"  (or: uv sync --all-extras)'
                ) from exc
            kwargs: dict[str, Any] = {}
            if self.region:
                kwargs["aws_region"] = self.region
            self._client = AnthropicBedrockMantle(**kwargs)
        return self._client

    def _ask(self, chunk: list[Cue]) -> str:
        client = self._get_client()
        response = client.messages.create(
            model=self.model,
            max_tokens=self.max_tokens,
            system=SYSTEM_PROMPT,
            output_config={"effort": self.effort},
            messages=[{"role": "user", "content": render_chunk(chunk, self.words_per_second)}],
        )
        stop = getattr(response, "stop_reason", None)
        if stop == "refusal":
            raise RuntimeError(f"model declined to rewrite this chunk: {stop}")
        if stop == "max_tokens":
            raise RuntimeError("reply hit max_tokens; lower --chunk-size")
        return "".join(
            block.text for block in response.content if getattr(block, "type", "") == "text"
        )

    def _simplify_chunk(self, chunk: list[Cue]) -> dict[int, str]:
        expected = {c.index for c in chunk}
        self.stats.chunks += 1
        got = self._attempt(chunk, expected)
        missing = expected - got.keys()
        if missing and len(chunk) > 1:
            # One retry, narrowed to just the cues that came back missing.
            self.stats.retries += 1
            retry_cues = [c for c in chunk if c.index in missing]
            got.update(self._attempt(retry_cues, missing))
        return got

    def _attempt(self, chunk: list[Cue], expected: set[int]) -> dict[int, str]:
        try:
            return parse_reply(self._ask(chunk), expected)
        except Exception as exc:  # one bad chunk must never lose the whole track
            message = f"cues {min(expected)}-{max(expected)}: {type(exc).__name__}: {exc}"
            log.warning("caption simplification failed for %s", message)
            self.stats.failures.append(message)
            return {}

    def simplify(self, vtt: str) -> str | None:
        cues, preamble = parse_vtt(vtt)
        if not cues:
            return None
        self.stats = SimplifyStats(cues=len(cues))

        rewritten: dict[int, str] = {}
        for start in range(0, len(cues), self.chunk_size):
            rewritten.update(self._simplify_chunk(cues[start : start + self.chunk_size]))

        out: list[Cue] = []
        for cue in cues:
            text = rewritten.get(cue.index)
            if text:
                self.stats.rewritten += 1
                out.append(cue.with_text(text))
            else:
                self.stats.kept_verbatim += 1
                out.append(cue)

        if self.stats.rewritten == 0:
            log.error("no cue could be simplified; not writing a simplified track")
            return None
        if self.stats.kept_verbatim:
            log.warning(
                "%d of %d cues kept their verbatim text",
                self.stats.kept_verbatim,
                self.stats.cues,
            )
        return build_vtt(out, preamble)
